name: Update developer token
on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-developer-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          curl -sSL https://music.apple.com/ \
          | grep 'desktop-music-app/config/environment' \
          | head \
          | node -p 'JSON.stringify({ developerToken: JSON.parse(decodeURIComponent(require("fs").readFileSync(0, "utf-8").match(/content="([^"]+)/)[1])).MEDIA_API.token }, null, 2)'
          | tee token.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
