name: Update developer token
on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-developer-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          curl -sSL https://music.apple.com/ \
          | grep 'desktop-music-app/config/environment' \
          | head \
          | node -p 'JSON.stringify({ developerToken: JSON.parse(decodeURIComponent(require("fs").readFileSync(0, "utf-8").match(/content="([^"]+)/)[1])).MEDIA_API.token }, null, 2)' \
          | tee token.json
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update developer token
          delete-branch: true
          base: main
          title: Update developer token
      - name: Enable pull request automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
