name: Update developer token
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-developer-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: scripts/update-developer-token.sh
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: '[Automated][CI Skip] Update developer token'
          delete-branch: true
          base: main
          title: '[Automated][CI Skip] Update developer token'
      - name: Merge pull request
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
          method: squash
